#!/bin/bash

#set -o errexit
set -o xtrace

DLADM_LINKS=$(dladm show-link -p -o link,state)
while read l
do
    RE="(.*):up"
    [[ ${l} =~ $RE ]] && LINKS="${BASH_REMATCH[1]} $LINKS"
done <<< "${DLADM_LINKS}"

method_start() {
    svcadm enable svc:/network/routing/ndp:default
    for link in $LINKS
    do
        ipadm create-addr -t -T addrconf ${link}/v6
    done
}

method_stop() {
    for link in $LINKS
    do
        ipadm delete-addr ${link}/v6
    done
}

method_$1
