#!/bin/bash

#set -o errexit
set -o xtrace

source /lib/svc/share/smf_include.sh

nics=( $(sysinfo | json 'Network Interfaces' | json -ka) )
vnics=( $(sysinfo | json 'Virtual Network Interfaces' | json -ka) )

method_start() {
    # Services are not recursively enabled at import
    # https://www.illumos.org/issues/5862
    svcadm enable svc:/network/routing/ndp:default
    for nic in "${nics[@]}" "${vnics[@]}"
    do
        ipadm create-addr -t -T addrconf "${nic}"/v6
    done
}

method_stop() {
    for nic in "${nics[@]}" "${vnics[@]}"
    do
        ipadm delete-addr "${nic}"/v6
    done
}

action=${*:$OPTIND:1}

case $action in
    start) method_start;;
    stop)  method_stop;;
    *)     exit "$SMF_EXIT_ERR_FATAL";;
esac

exit 0
