#!/bin/bash

#set -o errexit
set -o xtrace

source /lib/svc/share/smf_include.sh || true

usage() {
    echo "$0 -c <configuration> {start | stop}"
}

while getopts "c:" options
do
    case $options in
        c ) config="${OPTARG}";;
        h ) usage;;
        * ) usage; exit "$SMF_EXIT_ERR_FATAL";;
    esac
done

if ! [[ -f $config ]]; then
    usage
    exit "$SMF_EXIT_ERR_FATAL"
fi

method_start() {
    while read -a line
    do
        ipadm create-addr -t -T static -a local="${line[0]}" "${line[1]}"
    done < "${CONFIG}"
}

method_stop() {
    while read -a line
    do
        ipadm delete-addr "${line[1]}"
    done < "${CONFIG}"
}

action=${*:$OPTIND:1}

case $action in
    start) method_start;;
    stop)  method_stop;;
    *)     usage; exit "$SMF_EXIT_ERR_FATAL";;
esac

exit 0
