#!/bin/bash

#set -o errexit
set -o xtrace

source /lib/svc/share/smf_include.sh

DLADM_LINKS=$(dladm show-link -p -o link,state)
while read l
do
    RE="(.*):up"
    [[ "${l}" =~ $RE ]] && LINKS="${BASH_REMATCH[1]} $LINKS"
done <<< "${DLADM_LINKS}"

method_start() {
    # Services are not recursively enabled at import
    # https://www.illumos.org/issues/5862
    svcadm enable svc:/network/routing/ndp:default
    for link in $LINKS
    do
        ipadm create-addr -t -T addrconf "${link}"/v6
    done
}

method_stop() {
    for link in $LINKS
    do
        ipadm delete-addr "${link}"/v6
    done
}

action=${*:$OPTIND:1}

case $action in
    start) method_start;;
    stop)  method_stop;;
    *)     exit $SMF_EXIT_ERR_FATAL;;
esac

exit 0
